### ISSUE TITLE
"variable clip* not found" error

### ISSUE THREAD

**Issue by PaulFrissard** [asjadnaqvi/stata-clipgeo#2]
Hi Asjad, congrats for this new package!

I tried it with a shapefile of Mexico's municipalities that works well with spmap, but I get the following error message: 
variable clip* not found
r(111);

This is my code:
`cd "D:\Sembrando Vida\Mapeo"`
`spshape2dta "D:\INEGI\Marco geoestadístico\Marco geoestadístico 2020\MG_2020_Integrado\conjunto_de_datos\00mun", ///`
`replace saving(munest2020)`

`cd "D:\Sembrando Vida\Mapeo"`
`use munest2020, clear`
`spmap _ID using munest2020_shp, id(_ID)`
`clippolygon munest2020_shp, box(-7000,11000,330000,355000)`

Everything works fine, except clippolygon.

What characteristics this clip* variable should have?

Many thanks!

**Comment by asjadnaqvi** [comment]
Dear Paul,

You are using the clip extents that are defined for my example data which is Europe. For your data on Mexico, you need to open up the shapefile and figure out roughly what the extents are. I will add an additional check to see if the box is completely outside of the boundaries. It should throw an error.

**Comment by PaulFrissard** [comment]
Many thanks! Works perfect now :)
